[project]
name = "bookmarks"
version = "0.1.0"
description = "A simple bookmark manager for Django"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.7",
    "django-environ>=0.14.0",
    "django-extensions>=4.1",
    "django-taggit>=6.1.0",
    "easy-thumbnails>=2.10.1",
    "httpx>=0.28.1",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.4",
    "pyopenssl>=26.4.0",
    "pytils>=0.4.4",
    "requests>=2.34.2",
    "social-auth-app-django>=6.0.1",
]



[dependency-groups]
dev = [
    "django-debug-toolbar>=7.0.0",
    "ipython>=9.16.1",
    "werkzeug>=3.1.8",
]
[tool.uv]
package = false
